/**
 * Auto-generated by Supabase MCP
 * Database types for halloween-maps-2025
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      locations: {
        Row: {
          activity_details: string | null
          address: string
          created_at: string
          email: string | null
          has_activity: boolean
          has_candy: boolean
          id: string
          is_participating: boolean
          is_start: boolean
          latitude: number
          location_type: Database["public"]["Enums"]["location_type"]
          longitude: number
          modified_at: string | null
          phone_number: string | null
          route: Database["public"]["Enums"]["route"] | null
        }
        Insert: {
          activity_details?: string | null
          address: string
          created_at?: string
          email?: string | null
          has_activity?: boolean
          has_candy?: boolean
          id?: string
          is_participating?: boolean
          is_start?: boolean
          latitude: number
          location_type: Database["public"]["Enums"]["location_type"]
          longitude: number
          modified_at?: string | null
          phone_number?: string | null
          route?: Database["public"]["Enums"]["route"] | null
        }
        Update: {
          activity_details?: string | null
          address?: string
          created_at?: string
          email?: string | null
          has_activity?: boolean
          has_candy?: boolean
          id?: string
          is_participating?: boolean
          is_start?: boolean
          latitude?: number
          location_type?: Database["public"]["Enums"]["location_type"]
          longitude?: number
          modified_at?: string | null
          phone_number?: string | null
          route?: Database["public"]["Enums"]["route"] | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      location_type: "House" | "Table" | "Car" | "Parking" | "Refreshments" | "Store"
      route: "Over 8" | "Under 8" | "Toddlers"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
